name = "Winter 24"
version = "0.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1903257736533c28b516d06a7ba75ceef872a456b54b9ee27e24400fc023321a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
